import Invoice from "../models/Invoice.js";
import Stay from "../models/Stay.js";
import Expense from "../models/Expense.js";
import asyncHandler from "../utils/asyncHandler.js";
import ApiError from "../utils/ApiError.js";
import { sendInvoiceEmail } from "../services/emailService.js";

const makeInvoiceNumber = () => `INV-${Date.now()}`;

const normalizePayment = (totalAmount, rawPaymentStatus, rawAmountPaid) => {
  const paymentStatus = String(rawPaymentStatus || "unpaid").toLowerCase();
  const total = Number(totalAmount || 0);
  const amountPaid = Math.max(Number(rawAmountPaid || 0), 0);
  const remainingBalance = Math.max(0, total - amountPaid);
  return {
    paymentStatus: remainingBalance === 0 ? "paid" : paymentStatus,
    amountPaid,
    remainingBalance,
    paidStatus:
      remainingBalance === 0
        ? "Paid"
        : paymentStatus === "partial"
          ? "Partial"
          : "Unpaid",
  };
};

export const generateInvoice = asyncHandler(async (req, res, next) => {
  const {
    stayId,
    paymentMethod = "Cash",
    paymentStatus = "unpaid",
    paidStatus = "Unpaid",
    amountPaid = 0,
  } = req.body;
  const generatedBy = req.user?._id || req.body.generatedBy;
  if (!generatedBy) {
    return next(new ApiError(400, "Generated by user is required"));
  }
  const stay = await Stay.findById(stayId).populate("customer room employee");

  if (!stay) {
    return next(new ApiError(404, "Stay not found"));
  }

  const expenses = await Expense.find({ stay: stay._id });
  const expenseTotal = expenses.reduce(
    (sum, item) => sum + Number(item.total || 0),
    0,
  );
  const totalAmount = Number(stay.roomCharges || 0) + expenseTotal;
  const payment = normalizePayment(
    totalAmount,
    paymentStatus || paidStatus,
    amountPaid || stay.amountPaid || stay.paidAmount || 0,
  );

  const invoice = await Invoice.findOneAndUpdate(
    { stay: stay._id },
    {
      invoiceNumber: makeInvoiceNumber(),
      stay: stay._id,
      customer: stay.customer._id,
      room: stay.room._id,
      generatedBy,
      roomCharges: stay.roomCharges || 0,
      expenseTotal,
      totalAmount,
      paymentStatus: payment.paymentStatus,
      paidAmount: payment.amountPaid,
      remainingBalance: payment.remainingBalance,
      paidStatus: payment.paidStatus,
      paymentMethod,
      paidAt: payment.paymentStatus === "paid" ? new Date() : undefined,
    },
    { new: true, upsert: true },
  ).populate("customer room stay generatedBy");

  stay.totalExpenses = expenseTotal;
  stay.totalAmount = totalAmount;
  stay.paymentStatus = payment.paymentStatus;
  stay.amountPaid = payment.amountPaid;
  stay.remainingBalance = payment.remainingBalance;
  stay.paidStatus = payment.paidStatus;
  stay.paymentMethod = paymentMethod;
  await stay.save();

  res.status(201).json({ invoice });
});

export const listInvoices = asyncHandler(async (_req, res) => {
  const invoices = await Invoice.find()
    .populate("customer room stay generatedBy")
    .sort({ createdAt: -1 });
  res.json({ invoices });
});

export const getInvoiceById = asyncHandler(async (req, res, next) => {
  const invoice = await Invoice.findById(req.params.id).populate(
    "customer room stay generatedBy",
  );
  if (!invoice) {
    return next(new ApiError(404, "Invoice not found"));
  }

  const expenses = await Expense.find({ stay: invoice.stay._id }).sort({
    createdAt: -1,
  });
  res.json({ invoice, expenses });
});

export const markInvoicePaid = asyncHandler(async (req, res, next) => {
  const invoice = await Invoice.findByIdAndUpdate(
    req.params.id,
    {
      paymentStatus: "paid",
      paidAmount: Number(req.body.amountPaid || req.body.totalAmount || 0),
      remainingBalance: 0,
      paidStatus: "Paid",
      paidAt: new Date(),
      paymentMethod: req.body.paymentMethod || "Cash",
    },
    { new: true },
  );

  if (!invoice) {
    return next(new ApiError(404, "Invoice not found"));
  }

  res.json({ invoice });
});

export const sendInvoiceByEmail = asyncHandler(async (req, res, next) => {
  const invoice = await Invoice.findById(req.params.id).populate(
    "customer room stay generatedBy",
  );
  if (!invoice) {
    return next(new ApiError(404, "Invoice not found"));
  }

  if (!invoice.customer.email) {
    return next(new ApiError(400, "Customer email is missing"));
  }

  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.6">
      <h2>Hotel Invoice ${invoice.invoiceNumber}</h2>
      <p><strong>Customer:</strong> ${invoice.customer.fullName}</p>
      <p><strong>Room:</strong> ${invoice.room.roomNumber}</p>
      <p><strong>Total:</strong> ${invoice.totalAmount}</p>
      <p><strong>Status:</strong> ${invoice.paidStatus}</p>
    </div>
  `;

  await sendInvoiceEmail({
    to: invoice.customer.email,
    subject: `Invoice ${invoice.invoiceNumber}`,
    html,
  });

  res.json({ message: "Invoice email processed", invoiceId: invoice._id });
});
